name: testing this lame thing
favicon: null
layout_spectrum: 0.4817745443433523
typography_spectrum: 0.5705190747976303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0793582801707089
  lightness: 0.04312095185741782
  saturation: 0.699511467712
  rhythmicContrast: 0.13388267322443426
purpose: []
